// app.js — Shared utilities for Smart PDF Summarizer (ES module)
// Import in HTML pages instead of duplicating these functions inline.

// ── DOM helpers ──────────────────────────────────────────
export const $ = (id) => document.getElementById(id);

// ── Format file size ─────────────────────────────────────
export function fmtSize(bytes) {
  if (bytes < 1024) return bytes + ' B';
  if (bytes < 1048576) return (bytes / 1024).toFixed(1) + ' KB';
  return (bytes / 1048576).toFixed(2) + ' MB';
}

// ── Escape HTML ──────────────────────────────────────────
export function esc(str) {
  if (!str) return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// ── Strip title + footer from generated .md files ────────
export function stripMdBoilerplate(md) {
  if (!md) return '';
  return md
    .replace(/^# .+\n+/, '')
    .replace(/\n---\n> Generated by Smart PDF Summarizer[\s\S]*$/, '')
    .trim();
}

/** True when AI output is empty or only contains chunk-failure warnings. */
export function isIncompleteOutput(md) {
  if (!md) return true;
  const body = stripMdBoilerplate(md);
  if (!body) return true;
  if (/could not be processed/i.test(body)) return true;
  return false;
}

// ── Markdown to HTML (limited, safe) ─────────────────────
export function md2html(md) {
  if (!md) return '';
  let s = md
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/^---$/gm, '<hr/>')
    .replace(/^> (.+)$/gm, '<blockquote>$1</blockquote>')
    .replace(/^[-•*] (.+)$/gm, '<li>$1</li>');
  s = s.replace(/(<li>[^]*?<\/li>\n?)+/g, m => '<ul>' + m + '</ul>');
  s = s.split(/\n{2,}/).map(b => {
    b = b.trim();
    if (!b) return '';
    if (/^<(h[23]|ul|hr|blockquote)/.test(b)) return b;
    return '<p>' + b.replace(/\n/g, '<br/>') + '</p>';
  }).join('');
  return s;
}

// ── Format date ──────────────────────────────────────────
export function fmtDate(isoStr) {
  if (!isoStr) return '';
  const d = new Date(isoStr);
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) +
    ' at ' + d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
}

// ── Parse flashcards from markdown ───────────────────────
export function parseFlashcards(mdText) {
  const cards = [];
  let cur = null;
  for (const line of mdText.split('\n')) {
    const qm = line.match(/^\*\*Q:\*\*\s+(.+)/);
    const am = line.match(/^\*\*A:\*\*\s+(.+)/);
    if (qm) { cur = { q: qm[1], a: '' }; }
    else if (am && cur) { cur.a = am[1]; cards.push(cur); cur = null; }
  }
  return cards;
}

// ── Download blob as file ──────────────────────────────────
export function downloadBlob(content, filename) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ── Render document list with staggered animation ──────────
export function renderDocList(container, docItems, clickHandler) {
  container.innerHTML = '';
  docItems.forEach((doc, i) => {
    const div = document.createElement('div');
    div.className = 'doc-item';
    div.style.animationDelay = (i * 40) + 'ms';
    div.innerHTML = doc.html;
    if (clickHandler) {
      div.addEventListener('click', () => clickHandler(doc));
      div.tabIndex = 0;
      div.setAttribute('role', 'button');
      div.addEventListener('keydown', e => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          clickHandler(doc);
        }
      });
    }
    container.appendChild(div);
  });
}

// ── Render flashcards with keyboard accessibility ────────
export function renderFlashcards(container, cards, tFn) {
  const hint = tFn('clickToFlip'), lbl = tFn('card'), ansLabel = tFn('answerLabel');
  container.innerHTML = '';
  cards.forEach((fc, i) => {
    const div = document.createElement('div');
    div.className = 'fc';
    div.tabIndex = 0;
    div.setAttribute('role', 'button');
    div.setAttribute('aria-label', `${lbl} ${i+1}: ${fc.q}`);
    div.innerHTML = `<div class="fc-inner"><div class="fc-front"><div class="lbl">${lbl} ${i+1}</div><div class="q">${esc(fc.q)}</div><div class="fc-hint">${hint}</div></div><div class="fc-back"><div class="lbl">${ansLabel}</div><div class="a">${esc(fc.a)}</div><div class="fc-hint">${hint}</div></div></div>`;
    div.addEventListener('click', () => div.classList.toggle('flipped'));
    div.addEventListener('keydown', e => {
      if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); div.classList.toggle('flipped'); }
    });
    container.appendChild(div);
  });
}

// ── Parse quiz from markdown ─────────────────────────────
export function parseQuiz(mdText) {
  const questions = [];
  let cur = null;
  let options = [];
  let correctIdx = -1;
  let explanation = '';

  for (const line of mdText.split('\n')) {
    const qMatch = line.match(/^## Question (\d+)/);
    const optMatch = line.match(/^([A-D])\.\s+(.+)/);
    const correctMatch = line.match(/^\*\*Correct:\*\*\s+([A-D])/);
    const explMatch = line.match(/^\*\*Explanation:\*\*\s+(.+)/);

    if (qMatch) {
      if (cur && options.length > 0) {
        questions.push({ question: cur, options, correct_index: correctIdx, explanation });
      }
      cur = '';
      options = [];
      correctIdx = -1;
      explanation = '';
    } else if (optMatch) {
      options.push(optMatch[2]);
    } else if (correctMatch) {
      correctIdx = correctMatch[1].charCodeAt(0) - 65;
    } else if (explMatch) {
      explanation = explMatch[1];
    } else if (cur !== null && line.trim() && !line.startsWith('##')) {
      cur = (cur ? cur + ' ' : '') + line.trim();
    }
  }
  if (cur && options.length > 0) {
    questions.push({ question: cur, options, correct_index: correctIdx, explanation });
  }
  return questions;
}

// ── Render quiz with scoring ─────────────────────────────
export function renderQuiz(container, questions, tFn) {
  container.innerHTML = '';
  let score = 0;
  let answered = 0;

  const scoreEl = document.createElement('div');
  scoreEl.className = 'quiz-score';
  scoreEl.textContent = `0 / ${questions.length}`;
  container.appendChild(scoreEl);

  questions.forEach((q, i) => {
    const card = document.createElement('div');
    card.className = 'quiz-card';
    card.innerHTML = `
      <div class="quiz-q">${esc(q.question)}</div>
      <div class="quiz-options">
        ${q.options.map((opt, j) => `
          <button class="quiz-opt" data-idx="${j}" data-correct="${q.correct_index}">
            <span class="quiz-opt-letter">${String.fromCharCode(65 + j)}</span>
            <span class="quiz-opt-text">${esc(opt)}</span>
          </button>
        `).join('')}
      </div>
      <div class="quiz-explanation" style="display:none">${esc(q.explanation)}</div>
    `;

    card.querySelectorAll('.quiz-opt').forEach(btn => {
      btn.addEventListener('click', () => {
        if (card.classList.contains('answered')) return;
        card.classList.add('answered');
        answered++;

        const selected = parseInt(btn.dataset.idx);
        const correct = parseInt(btn.dataset.correct);

        if (selected === correct) {
          btn.classList.add('correct');
          score++;
        } else {
          btn.classList.add('wrong');
          card.querySelector(`[data-idx="${correct}"]`).classList.add('correct');
        }

        card.querySelector('.quiz-explanation').style.display = 'block';
        scoreEl.textContent = `${score} / ${questions.length}`;
        if (answered === questions.length) {
          scoreEl.classList.add('quiz-complete');
        }
      });
    });

    container.appendChild(card);
  });
}
